
# Área de estudio

El río Paraná es el segundo río más largo de América del Sur, con 4000 km @Bonetto1986. En Argentina, es el límite natural de múltiples provincias, hasta llegar al Río de la Plata, para terminar en el Océano Atlántico. El río Paraguay, con 2550 km @Bonetto1986, es un afluente del río Paraná, en su cuenca media, en el Noreste argentino. La alta presencia de sólidos en el río Paraguay que se descargan en el río Paraná, cambia las características de la composición de este último, creando dos regiones distintas de alta (oeste) y baja (este) concentración de sedimentos @Lane2008.

El Paraná tiene un gran impacto en la sociedad del AMGR, específicamente sobre la industria pesquera, el turismo, las actividades recreativas de la población local y las rutas de transporte @Neiff2005. Es la fuente principal de agua de la planta potabilizadora de la provincia. Dicha planta posee dos tomas de agua cruda ubicada en distintos sectores del mencionado río. Una de ellas, la más antigua, está construida sobre un brazo del río Paraná, el río Barranqueras; éste, a su vez, está conectado con dos ríos principales del AMGR que son los ríos Negro y Tragadero. A fines del 2023, entró en operaciones la nueva toma situada sobre el canal principal de navegación del río Paraná, en una zona cercana al puente Gral. Belgrano, que une las provincias de Chaco y Corrientes.

Dada la gran variabilidad en la cantidad de sedimentos presentes en el agua del Paraná, la planta potabilizadora necesita adaptar frecuentemente la operación de filtración; ésta es una etapa crítica del proceso, debido a la necesidad de dosificar agentes floculantes para asegurar la remoción de los sólidos.  La aplicación de las técnicas de teledetección, en la recuperación de los datos espectrales del agua, tiene como objetivo crear un modelo que los estime de forma remota; asimismo, esas técnicas le brindarían a la empresa herramientas valiosas para la toma de decisiones.  

