
# Área de estudio {#sec-roi}

El río Paraná es el segundo río más largo de América del Sur, con 4000 km @Bonetto1986. En Argentina, es el límite natural de múltiples provincias, hasta llegar al Río de la Plata, para terminar en el Océano Atlántico. El Paraná, posee un módulo anual de 17.300 m3/s producto de los aportes del río Alto Paraná (en la República de Paraguay) y del río Paraguay @Espinola2020. Este último, con 2550 km @Bonetto1986, es un afluente del río Paraná, en su cuenca media, en el Noreste argentino. 

El río Paraguay recibe del río Bermejo un volumen considerable de sedimentos finos en suspensión, provenientes de la Cordillera de los Andes que se descargan en el río Paraná  @Amsler2009, @Orfeo2002. A partir de la confluencia con el río Paraguay (frente a la localidad de Paso de la Patria, provincia de Corrientes), el río Paraná muestra marcadas diferencias espaciales y temporales en las concentraciones de esos sedimentos que modifican las características de la composición del agua. Debido a ello se generan dos regiones distintas: de alta (oeste) y baja (este) concentración de dichos sedimentos en suspensión @Lane2008.

Debido a las concentraciones tan dispares mencionadas en el párrafo anterior, la interfaz de mezcla entre las aguas donde dos grandes ríos se unen se puede visualizar claramente. No obstante, esa mezcla completa comúnmente requiere una longitud de río significativa y esa distancia puede extenderse a decenas e incluso cientos de kilómetros. Las observaciones de campo de la unión de los ríos Paraná y Paraguay, muestran que la longitud de mezcla puede ser mayor a 400 km (mezcla lenta) pero también tan baja como 8 km (mezcla rápida) @Lane2008. En general, la visualización sólo puede manifestarse mediante mediciones de campo y datos de sensado remoto @Mackay1970, @Krouse1971, @Matsui1976, @Stallard1987.

A partir de la confluencia mencionada y su planicie de inundación, el río Paraná incorpora varios m3/s en términos de caudales medios. El aporte de esos caudales es uno de los factores que altera el ciclo hidrológico; los otros que también pueden incidir son: 
- Los parámetros como pH, temperatura, sólidos en suspensión, conductividad y turbidez también involucran procesos que los afectan @RodriguesCapitulo2022.
- Las oscilaciones vinculadas a cambios climáticos a escala global como por ejemplo el ENOS (El Niño oscilación sur) en nuestro país @Pasquini2011, @Bohn2016, @Lovino2018, @DelaCasa2021. 
- Los efectos antrópicos @Molfino2021, @Ferreira2020,  @RomeroAcuna2020,  @Abrial2021 modifican los procesos físico-químicos de los hábitats y los patrones de las comunidades biológicas, producen períodos de inundación, sequía y variaciones extremas del caudal (flujos bajos, altos, extremadamente altos, etc.). 


El Paraná tiene un gran impacto en la sociedad del AMGR, específicamente sobre la industria pesquera, el turismo, las actividades recreativas de la población local y las rutas de transporte @Neiff2005. Es el recurso hídrico requerido por la planta potabilizadora, cuyas tomas de agua cruda están ubicadas en dos sectores del mencionado río. Una de ellas, la más antigua, está ubicada sobre un brazo del río Paraná, el río Barranqueras; éste, a su vez, está conectado con dos ríos principales del área metropolitana que son los ríos Negro y Tragadero. A fines del 2023, entró en operaciones la nueva toma de agua situada sobre el canal principal de navegación del río Paraná, en una zona cercana al puente Gral. Belgrano que une las provincias de Chaco y Corrientes.

Dada la gran variabilidad en la cantidad de sedimentos presentes en el agua del Paraná, la planta potabilizadora necesita adaptar frecuentemente la operación de filtración; ésta es una etapa crítica del proceso, debido a la necesidad de dosificar agentes floculantes para asegurar la remoción de los sólidos.  La aplicación de las técnicas de teledetección, en la recuperación de los datos espectrales del agua, tiene como objetivo crear un modelo que los estime de forma remota; asimismo, esas técnicas le brindarían a la empresa herramientas valiosas para la toma de decisiones.  



